// <auto-generated />
namespace AplicacionMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addModelDocumentType_Employe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addModelDocumentType_Employe));
        
        string IMigrationMetadata.Id
        {
            get { return "202004020019085_addModelDocumentType_Employe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
